UPDATE QLDA.QLDA_NHANVIEN
SET LUONG = '1300', PHUCAP = '1700'
WHERE MANV = 'NV200';

SELECT * FROM QLDA.QLDA_PHANCONG;
UPDATE QLDA.QLDA_PHANCONG
SET THOIGIAN = TO_DATE('13/1/2023', 'DD/MM/YYYY')
--SET MADA = 'DP11111'
WHERE MANV = 'NV001';
SELECT * FROM QLDA.qlda_nhanvien WHERE MANV = 'NV302';
SELECT NV1.*, QLDA.encrypt_decrypt.decrypt_nhanvien_luong(luong, QLDA.ENCRYPT_DECRYPT.CREATE_KEY((SELECT MANV FROM QLDA.QLDA_NHANVIEN NV2 WHERE NV1.MANV = NV2.MANV), QLDA.ENCRYPT_DECRYPT.SEQ_NUM)) AS luong_giaima,
QLDA.encrypt_decrypt.decrypt_nhanvien_phucap(phucap, QLDA.ENCRYPT_DECRYPT.CREATE_KEY((SELECT MANV FROM QLDA.QLDA_NHANVIEN NV2 WHERE NV1.MANV = NV2.MANV), QLDA.ENCRYPT_DECRYPT.SEQ_NUM)) AS phucap_giaima FROM QLDA.QLDA_NHANVIEN NV1;
