CONNECT QLDA/admin123;
---ROLE TAICHINH

CREATE ROLE TC;
CREATE USER  TC001 IDENTIFIED BY TC001;
GRANT CONNECT TO TC;
GRANT TC TO TC001;

--Xem toàn bộ trên quan hệ NHANVIEN
GRANT SELECT ON QLDA.QLDA_NHANVIEN TO TC;

--Xem toàn bộ trên quan hệ PHANCONG
GRANT SELECT ON QLDA.QLDA_PHANCONG TO TC;

--Có thể sửa trên thuộc tính LUONG va PHUCAP
GRANT UPDATE(LUONG, PHUCAP) ON QLDA.QLDA_NHANVIEN TO TC;
CREATE OR REPLACE VIEW V_NV_PC
AS
SELECT PC.*
FROM QLDA.QLDA_NHANVIEN NV, QLDA.QLDA_PHANCONG PC
WHERE NV.MANV = PC.MANV AND NV.MANQL = SYS_CONTEXT('userenv', 'session_user');