CONNECT QLDA/admin123;
--ROLE NHANSU
alter session set "_ORACLE_SCRIPT"=true;
CREATE ROLE NS;
CREATE USER  NS001 IDENTIFIED BY NS001;
GRANT CONNECT TO NS;
GRANT NS TO NS001;
grant select on QLDA.QLDA_PHANCONG to NS; --Đã cài chính sách VPD ở CS1

CREATE USER  NS002 IDENTIFIED BY NS002;
GRANT NS TO NS002;

--CÓ quyền thêm, cập nhận trên quan hệ PHONGBAN
GRANT SELECT ON QLDA.QLDA_PHONGBAN TO NS;
GRANT INSERT, UPDATE ON QLDA.QLDA_PHONGBAN TO NS;

--Tạo view để NS chỉ thấy được LUONG, PHUCAP của mình
CREATE OR REPLACE VIEW V_QLDA_NHANVIEN_NS
AS
SELECT
    MANV, TENNV, PHAI, NGAYSINH, DIACHI, SODT,
    DECODE(MANV, USER, LUONG, NULL) AS LUONG,
    DECODE(MANV, USER, PHUCAP, NULL) AS PHUCAP,
    VAITRO, MANQL, MAPB
FROM QLDA.QLDA_NHANVIEN;

GRANT SELECT ON QLDA.V_QLDA_NHANVIEN_NS TO NS;
GRANT INSERT(MANV, TENNV, PHAI, NGAYSINH, DIACHI, SODT, VAITRO, MANQL, MAPB) ON QLDA.V_QLDA_NHANVIEN_NS TO NS;
GRANT UPDATE(MANV, TENNV, PHAI, NGAYSINH, DIACHI, SODT, VAITRO, MANQL, MAPB) ON QLDA.V_QLDA_NHANVIEN_NS TO NS;
SELECT * FROM QLDA.V_QLDA_NHANVIEN_NS;

--Cách xem phân quyền trên cột của View
SELECT * FROM USER_COL_PRIVS WHERE TABLE_NAME LIKE 'V_QLDA_%' OR TABLE_NAME LIKE 'QLDA_%';