CONNECT QLDA/admin123;
--ROLE NHANSU
CREATE ROLE NS;
CREATE USER  NS001 IDENTIFIED BY NS001;
GRANT CONNECT TO NS;
GRANT NS TO NS001;

--CÓ quyền thêm, cập nhận trên quan hệ PHONGBAN
GRANT SELECT ON QLDA.QLDA_PHONGBAN TO NS;
GRANT INSERT, UPDATE ON QLDA.QLDA_PHONGBAN TO NS;

--Tạo view để NS chỉ thấy được LUONG, PHUCAP của mình
CREATE OR REPLACE VIEW V_QLDA_NHANVIEN_NS
AS
SELECT
    MANV, TENNV, PHAI, NGAYSINH, DIACHI, SODT,
    DECODE(MANV, USER, LUONG, NULL) LUONG,
    DECODE(MANV, USER, PHUCAP, NULL) PHUCAP,
    VAITRO, MANQL, MAPB
FROM QLDA.QLDA_NHANVIEN;

GRANT SELECT ON QLDA.V_QLDA_NHANVIEN_NS TO NS;
GRANT INSERT(MANV, TENNV, PHAI, NGAYSINH, DIACHI, SODT, VAITRO, MANQL, MAPB) ON QLDA.V_QLDA_NHANVIEN_NS TO NS;
GRANT UPDATE(MANV, TENNV, PHAI, NGAYSINH, DIACHI, SODT, VAITRO, MANQL, MAPB) ON QLDA.V_QLDA_NHANVIEN_NS TO NS;
SELECT * FROM QLDA.V_QLDA_NHANVIEN_NS;