ALTER SYSTEM SET db_create_file_dest = 'E:\';
create pluggable database PDB1 admin user QLDA_OLS identified by admin123;
ALTER PLUGGABLE DATABASE PDB1 OPEN;
--ALTER PLUGGABLE DATABASE CLOSE IMMEDIATE;
ALTER SESSION SET CONTAINER = PDB1;
--alter session set "_ORACLE_SCRIPT"=true;
--ALTER SESSION SET CONTAINER = CDB$ROOT;
--SHOW CON_NAME;
EXEC LBACSYS.CONFIGURE_OLS;
EXEC LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS;

GRANT INHERIT PRIVILEGES ON USER QLDA_OLS TO LBACSYS;
GRANT INHERIT PRIVILEGES ON USER SYS TO LBACSYS;
select name, status, description from dba_ols_status;

--Sau đó phải tắt đi, bật lại SQL Dev, và chạy câu lệnh alter session ... trên
--create public database link PDB01 using 'PDB01';
CREATE USER QLDA_PDB1 IDENTIFIED BY admin123;
GRANT CREATE SESSION TO QLDA_PDB1;
GRANT CREATE TABLE, UNLIMITED TABLESPACE TO QLDA_PDB1;
GRANT INHERIT PRIVILEGES ON USER SYS TO QLDA_PDB1;
--GRANT SA_SYSDBA TO QLDA_PDB1;

--Tạo 5 user này trên cả CDB$ROOT và PDB1
CREATE USER TP001 IDENTIFIED BY TP001; --Trưởng phòng phụ trách lĩnh vực sản xuất miền Nam (câu a)
CREATE USER TP002 IDENTIFIED BY TP002; --Trưởng phòng phụ trách tất cả các lĩnh vực không phân biệt chi nhánh (câu b).
CREATE USER TP003 IDENTIFIED BY TP003; --Trưởng phòng phụ trách lĩnh vực sản xuất ở miền Trung (câu c).
CREATE USER GD001 IDENTIFIED BY GD001; --Giám đốc có thể xem toàn bộ dữ liệu (câu a)
CREATE USER GD002 IDENTIFIED BY GD002; --Giám đốc phụ trách bất kỳ lĩnh vực nào ở chi nhánh miền Bắc (câu a)
CREATE USER NV001 IDENTIFIED BY NV001; --Nhân viên miền trung phụ trách tất cả lĩnh vực (thêm)
CREATE USER NV002 IDENTIFIED BY NV002; --Nhân viên phụ trách lĩnh vực gia công miền nam (thêm)
/*
DROP USER TP001;
DROP USER TP002;
DROP USER TP003;
DROP USER GD001;
DROP USER GD002;
*/

--Chỉ tạo role GD trên CDB$ROOT
GRANT TP TO TP001;
GRANT TP TO TP002;
GRANT TP TO TP003;
CREATE ROLE GD;
GRANT GD TO GD001;
GRANT GD TO GD002;

--Grant quyền đọc 4 bảng cho GD (cs7), grant trên CDB$root
GRANT SELECT ON QLDA.V_QLDA_NHANVIEN TO GD;
GRANT SELECT ON QLDA.QLDA_PHONGBAN TO GD;
GRANT SELECT ON QLDA.QLDA_DEAN TO GD;
GRANT SELECT ON QLDA.QLDA_PHANCONG TO GD;

--Grant quyền trên CDB$ROOT
GRANT CONNECT TO TP;
GRANT CONNECT TO GD;

--Grant quyền 5 user này trên PDB1
GRANT CREATE SESSION TO TP001;
GRANT CREATE SESSION TO TP002;
GRANT CREATE SESSION TO TP003;
GRANT CREATE SESSION TO GD001;
GRANT CREATE SESSION TO GD002;
GRANT CREATE SESSION TO NV001;
GRANT CREATE SESSION TO NV002;

/*
DROP USER TP001 CASCADE;
DROP USER TP002 CASCADE;
DROP USER TP003 CASCADE;
DROP USER GD001 CASCADE;
DROP USER GD002 CASCADE;
*/

EXECUTE SA_SYSDBA.CREATE_POLICY('OLS_QLDA', 'OLS_THONGBAO', 'NO_CONTROL');


GRANT OLS_QLDA_DBA TO QLDA_PDB1;
GRANT EXECUTE ON SA_COMPONENTS TO QLDA_PDB1;
GRANT EXECUTE ON SA_LABEL_ADMIN TO QLDA_PDB1;
GRANT EXECUTE ON SA_POLICY_ADMIN TO QLDA_PDB1;
GRANT EXECUTE ON SA_USER_ADMIN TO QLDA_PDB1;
GRANT EXECUTE ON CHAR_TO_LABEL TO QLDA_PDB1;

--EXECUTE SA_SYSDBA.DROP_POLICY('OLS_QLDA');
--Từ bước này đăng nhập user QLDA_PDB1/admin123;
CREATE TABLE THONGBAO(
    MaTB INT,
    NoiDung NVARCHAR2(100),
    ThoiGian TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DiaDiem NVARCHAR2(50),
    CONSTRAINT PK_THONGBAO PRIMARY KEY(MaTB)
);
--DROP TABLE THONGBAO;
INSERT INTO QLDA_PDB1.THONGBAO (MaTB, NoiDung, DiaDiem) VALUES (1, 'Đây là thông báo cho trưởng phòng phụ trách lĩnh vực sản xuất miền Nam', 'Miền Nam');
INSERT INTO QLDA_PDB1.THONGBAO (MaTB, NoiDung, DiaDiem) VALUES (2, 'Đây là thông báo cho trưởng phòng phụ trách bất kì lĩnh vực không phân biệt chi nhánh', NULL);
INSERT INTO QLDA_PDB1.THONGBAO (MaTB, NoiDung, DiaDiem) VALUES (3, 'Đây là thông báo cho trưởng phòng phụ trách lĩnh vực sản xuất ở miền Trung', 'Miền Trung');
INSERT INTO QLDA_PDB1.THONGBAO (MaTB, NoiDung, DiaDiem) VALUES (4, 'Đây là thông báo cho giám đốc có thể xem toàn bộ dữ liệu', NULL);
INSERT INTO QLDA_PDB1.THONGBAO (MaTB, NoiDung, DiaDiem) VALUES (5, 'Đây là thông báo cho giám đốc phụ trách bất kỳ lĩnh vực nào ở chi nhánh miền Bắc', 'Miền Bắc');
INSERT INTO QLDA_PDB1.THONGBAO (MaTB, NoiDung, DiaDiem) VALUES (6, 'Đây là thông báo cho trưởng phòng phụ trách bất kỳ lĩnh vực nào ở chi nhánh miền Nam', 'Miền Nam');
INSERT INTO QLDA_PDB1.THONGBAO (MaTB, NoiDung, DiaDiem) VALUES (7, 'Đây là thông báo cho nhân viên phụ trách bất kỳ lĩnh vực nào ở chi nhánh miền Trung', 'Miền Trung');
INSERT INTO QLDA_PDB1.THONGBAO (MaTB, NoiDung, DiaDiem) VALUES (8, 'Đây là thông báo cho nhân viên phụ trách lĩnh vực gia công không phân biệt chi nhánh', NULL);
--INSERT INTO QLDA_PDB1.THONGBAO (MaTB, NoiDung, DiaDiem) VALUES (9, 'Đây là thông báo cho nhân viên phụ trách cả 2 lĩnh vực gia công và sản xuất ở miền Bắc hoặc Trung', NULL);
COMMIT;

GRANT SELECT ON QLDA_PDB1.THONGBAO TO TP001;
GRANT SELECT ON QLDA_PDB1.THONGBAO TO TP002;
GRANT SELECT ON QLDA_PDB1.THONGBAO TO TP003;
GRANT SELECT ON QLDA_PDB1.THONGBAO TO GD001;
GRANT SELECT ON QLDA_PDB1.THONGBAO TO GD002;
GRANT SELECT ON QLDA_PDB1.THONGBAO TO NV001;
GRANT SELECT ON QLDA_PDB1.THONGBAO TO NV002;

SELECT * FROM THONGBAO;

EXECUTE SA_COMPONENTS.CREATE_LEVEL('OLS_QLDA', 300, 'GD', 'GIAM_DOC');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('OLS_QLDA', 200, 'TP', 'TRUONG_PHONG');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('OLS_QLDA', 100, 'NV', 'NHAN_VIEN');
/*
EXECUTE SA_COMPONENTS.DROP_LEVEL('OLS_QLDA', 300)
EXECUTE SA_COMPONENTS.DROP_LEVEL('OLS_QLDA', 200)
EXECUTE SA_COMPONENTS.DROP_LEVEL('OLS_QLDA', 100)
*/
--Xem owner của nhãn
SELECT * FROM SYS.SA_LABELS;

EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('OLS_QLDA', 50, 'MB', 'MUA_BAN');
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('OLS_QLDA', 40, 'SX', 'SAN_XUAT');
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('OLS_QLDA', 30, 'GC', 'GIA_CONG');
/*
EXECUTE SA_COMPONENTS.DROP_COMPARTMENT('OLS_QLDA', 50);
EXECUTE SA_COMPONENTS.DROP_COMPARTMENT('OLS_QLDA', 40);
EXECUTE SA_COMPONENTS.DROP_COMPARTMENT('OLS_QLDA', 30);
*/

EXECUTE SA_COMPONENTS.CREATE_GROUP('OLS_QLDA', 500, 'B', 'MIEN_BAC');
EXECUTE SA_COMPONENTS.CREATE_GROUP('OLS_QLDA', 450, 'T', 'MIEN_TRUNG');
EXECUTE SA_COMPONENTS.CREATE_GROUP('OLS_QLDA', 400, 'N', 'MIEN_NAM');
/*
EXECUTE SA_COMPONENTS.DROP_GROUP('OLS_QLDA', 500);
EXECUTE SA_COMPONENTS.DROP_GROUP('OLS_QLDA', 450);
EXECUTE SA_COMPONENTS.DROP_GROUP('OLS_QLDA', 400);
*/
--Nhãn giám đốc đọc tất cả dữ liệu
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_QLDA', 1000, 'GD'); 
--Nhãn giám đốc đọc dữ liệu miền Bắc
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_QLDA', 990, 'GD::B'); 
--Nhãn giám đốc đọc dữ liệu miền Trung
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_QLDA', 980, 'GD::T'); 
--Nhãn giám đốc đọc dữ liệu miền Nam
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_QLDA', 970, 'GD::N'); 
--Nhãn trưởng phòng sản xuất miền Bắc
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_QLDA', 900, 'TP:SX:B'); 
--Nhãn trưởng phòng sản xuất miền Trung
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_QLDA', 890, 'TP:SX:T'); 
--Nhãn trưởng phòng sản xuất miền Nam
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_QLDA', 880, 'TP:SX:N'); 
--Nhãn trưởng phòng
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_QLDA', 870, 'TP');
--Nhãn trưởng phòng tất cả lĩnh vực chi nhánh miền Nam
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_QLDA', 860, 'TP::N');
--Nhãn nhân viên miền trung
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_QLDA', 800, 'NV::T');
--Nhãn nhân viên gia công khu vực miền bắc
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_QLDA', 790, 'NV:GC:B'); 
--Nhãn nhân viên gia công
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_QLDA', 780, 'NV:GC'); 
--Nhãn nhân viên cả 2 lĩnh vực gia công và sản xuất ở miền Bắc hoặc Trung
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_QLDA', 770, 'NV:GC,SX:B,T'); 
/*
EXECUTE SA_LABEL_ADMIN.DROP_LABEL('OLS_QLDA', 1000);
EXECUTE SA_LABEL_ADMIN.DROP_LABEL('OLS_QLDA', 990);
EXECUTE SA_LABEL_ADMIN.DROP_LABEL('OLS_QLDA', 980);
EXECUTE SA_LABEL_ADMIN.DROP_LABEL('OLS_QLDA', 970);
EXECUTE SA_LABEL_ADMIN.DROP_LABEL('OLS_QLDA', 900);
EXECUTE SA_LABEL_ADMIN.DROP_LABEL('OLS_QLDA', 890);
EXECUTE SA_LABEL_ADMIN.DROP_LABEL('OLS_QLDA', 880);
EXECUTE SA_LABEL_ADMIN.DROP_LABEL('OLS_QLDA', 870);
EXECUTE SA_LABEL_ADMIN.DROP_LABEL('OLS_QLDA', 860);
EXECUTE SA_LABEL_ADMIN.DROP_LABEL('OLS_QLDA', 800);
EXECUTE SA_LABEL_ADMIN.DROP_LABEL('OLS_QLDA', 790);
EXECUTE SA_LABEL_ADMIN.DROP_LABEL('OLS_QLDA', 780);
EXECUTE SA_LABEL_ADMIN.DROP_LABEL('OLS_QLDA', 770);
*/

BEGIN
SA_POLICY_ADMIN.APPLY_TABLE_POLICY(
    POLICY_NAME  => 'OLS_QLDA',
    SCHEMA_NAME  => 'QLDA_PDB1',
    TABLE_NAME  => 'THONGBAO',
    TABLE_OPTIONS  => NULL
);
END;
/
UPDATE QLDA_PDB1.THONGBAO SET OLS_THONGBAO=CHAR_TO_LABEL('OLS_QLDA', 'TP:SX:N') WHERE MaTB=1;
UPDATE QLDA_PDB1.THONGBAO SET OLS_THONGBAO=CHAR_TO_LABEL('OLS_QLDA', 'TP') WHERE MaTB=2;
UPDATE QLDA_PDB1.THONGBAO SET OLS_THONGBAO=CHAR_TO_LABEL('OLS_QLDA', 'TP:SX:T') WHERE MaTB=3;
UPDATE QLDA_PDB1.THONGBAO SET OLS_THONGBAO=CHAR_TO_LABEL('OLS_QLDA', 'GD') WHERE MaTB=4;
UPDATE QLDA_PDB1.THONGBAO SET OLS_THONGBAO=CHAR_TO_LABEL('OLS_QLDA', 'GD::B') WHERE MaTB=5;
UPDATE QLDA_PDB1.THONGBAO SET OLS_THONGBAO=CHAR_TO_LABEL('OLS_QLDA', 'TP::N') WHERE MaTB=6;
UPDATE QLDA_PDB1.THONGBAO SET OLS_THONGBAO=CHAR_TO_LABEL('OLS_QLDA', 'NV::T') WHERE MaTB=7;
UPDATE QLDA_PDB1.THONGBAO SET OLS_THONGBAO=CHAR_TO_LABEL('OLS_QLDA', 'NV:GC') WHERE MaTB=8;
UPDATE QLDA_PDB1.THONGBAO SET OLS_THONGBAO=CHAR_TO_LABEL('OLS_QLDA', 'NV:GC,SX:B,T') WHERE MaTB=9;
COMMIT;

SELECT * FROM QLDA_PDB1.THONGBAO;


BEGIN
SA_POLICY_ADMIN.REMOVE_TABLE_POLICY(
    POLICY_NAME  => 'OLS_QLDA',
    SCHEMA_NAME  => 'QLDA_PDB1',
    TABLE_NAME  => 'THONGBAO',
    DROP_COLUMN => FALSE
);
END;
/
BEGIN
SA_POLICY_ADMIN.APPLY_TABLE_POLICY(
    POLICY_NAME  => 'OLS_QLDA',
    SCHEMA_NAME  => 'QLDA_PDB1',
    TABLE_NAME  => 'THONGBAO',
    TABLE_OPTIONS  => 'READ_CONTROL, WRITE_CONTROL, CHECK_CONTROL'
);
END;
/
--Gán nhãn người dùng

--GD001: Giám đốc (câu a)
BEGIN
SA_USER_ADMIN.SET_USER_LABELS(
    POLICY_NAME  =>'OLS_QLDA',
    USER_NAME  => 'GD001',
    MAX_READ_LABEL  => 'GD:MB,SX,GC:B,T,N',
    MAX_WRITE_LABEL  => 'GD:MB,SX,GC:B,T,N'
);
END;
/
--GD002: Giám đốc miền bắc (câu a)
BEGIN
SA_USER_ADMIN.SET_USER_LABELS(
    POLICY_NAME  =>'OLS_QLDA',
    USER_NAME  => 'GD002',
    MAX_READ_LABEL  => 'GD:MB,SX,GC:B',
    MAX_WRITE_LABEL  => 'GD:MB,SX,GC:B'
);
END;
/
--TP001: Trưởng phòng phụ trách lĩnh vực sản xuất miền Nam (câu a)
BEGIN
SA_USER_ADMIN.SET_USER_LABELS(
    POLICY_NAME  =>'OLS_QLDA',
    USER_NAME  => 'TP001',
    MAX_READ_LABEL  => 'TP:SX:N',
    MAX_WRITE_LABEL  => 'TP:SX:N'
);
END;
/
--TP002: trưởng phòng phụ trách tất cả các lĩnh vực không phân biệt chi nhánh (câu b).
BEGIN
SA_USER_ADMIN.SET_USER_LABELS(
    POLICY_NAME  =>'OLS_QLDA',
    USER_NAME  => 'TP002',
    MAX_READ_LABEL  => 'TP:MB,SX,GC:B,T,N',
    MAX_WRITE_LABEL  => 'TP:MB,SX,GC:B,T,N'
);
END;
/
--TP003: trưởng phòng phụ trách lĩnh vực sản xuất ở miền Trung (câu c).
BEGIN
SA_USER_ADMIN.SET_USER_LABELS(
    POLICY_NAME  =>'OLS_QLDA',
    USER_NAME  => 'TP003',
    MAX_READ_LABEL  => 'TP:SX:T',
    MAX_WRITE_LABEL  => 'TP:SX:T'
);
END;
/
--NV001: Nhân viên miền trung phụ trách tất cả lĩnh vực (thêm)
BEGIN
SA_USER_ADMIN.SET_USER_LABELS(
    POLICY_NAME  =>'OLS_QLDA',
    USER_NAME  => 'NV001',
    MAX_READ_LABEL  => 'NV:MB,SX,GC:T',
    MAX_WRITE_LABEL  => 'NV:MB,SX,GC:T'
);
END;
/
--NV002: Nhân viên phụ trách lĩnh vực gia công miền nam (thêm)
BEGIN
SA_USER_ADMIN.SET_USER_LABELS(
    POLICY_NAME  =>'OLS_QLDA',
    USER_NAME  => 'NV002',
    MAX_READ_LABEL  => 'NV:GC:N',
    MAX_WRITE_LABEL  => 'NV:GC:N'
);
END;

SELECT * FROM QLDA_PDB1.THONGBAO;


