drop table QLDA_PHONGBAN CASCADE CONSTRAINTS;
drop table QLDA_NHANVIEN CASCADE CONSTRAINTS;
drop table QLDA_DEAN CASCADE CONSTRAINTS;
drop table QLDA_PHANCONG CASCADE CONSTRAINTS;

CREATE TABLE QLDA_PHONGBAN(
    MAPB CHAR(7) PRIMARY KEY,
    TENPB VARCHAR2(30),
    TRPHG CHAR(7)
);

CREATE TABLE QLDA_NHANVIEN(
    MANV CHAR(7) PRIMARY KEY,
    TENNV VARCHAR2(30),
    PHAI VARCHAR2(3),
    NGAYSINH DATE,
    DIACHI VARCHAR2(40),
    SODT CHAR(10),
    LUONG FLOAT,
    PHUCAP FLOAT,
    VAITRO VARCHAR2(20),
    MANQL CHAR(7),
    MAPB CHAR(7) REFERENCES QLDA_PHONGBAN(MAPB)
);

CREATE TABLE QLDA_DEAN(
    MADA CHAR(7) PRIMARY KEY,
    TENDA VARCHAR2(40),
    NGAYBD DATE,
    PHONG CHAR(7) REFERENCES QLDA_PHONGBAN(MAPB)
);

CREATE TABLE QLDA_PHANCONG(
    MANV CHAR(7) REFERENCES QLDA_NHANVIEN(MANV),
    MADA CHAR(7) REFERENCES QLDA_DEAN(MADA),
    THOIGIAN DATE,
    CONSTRAINT PHCONG_PK PRIMARY KEY(MANV, MADA)
);

ALTER TABLE QLDA_PHONGBAN ADD CONSTRAINT TRPHG_FK FOREIGN KEY (TRPHG) REFERENCES QLDA_NHANVIEN(MANV);
ALTER TABLE QLDA_NHANVIEN ADD CONSTRAINT MANQL_FK FOREIGN KEY (MANQL) REFERENCES QLDA_NHANVIEN(MANV);
SELECT *
  FROM user_cons_columns WHERE table_name = 'QLDA_NHANVIEN' OR table_name = 'QLDA_PHONGBAN' or table_name ='QLDA_DEAN' or table_name = 'QLDA_PHANCONG';