CONNECT QLDA/admin123;

CREATE TABLE QLDA_PHONGBAN(
    MAPB CHAR(7) PRIMARY KEY,
    TENPB VARCHAR2(30),
    TRPHG VARCHAR2(30)
);

CREATE TABLE QLDA_NHANVIEN(
    MANV VARCHAR2(30) PRIMARY KEY,
    TENNV VARCHAR2(30),
    PHAI VARCHAR2(4),
    NGAYSINH DATE,
    DIACHI VARCHAR2(40),
    SODT CHAR(10),
    LUONG FLOAT,
    PHUCAP FLOAT,
    VAITRO VARCHAR2(20),
    MANQL CHAR(7),
    MAPB CHAR(7)
);

CREATE TABLE QLDA_DEAN(
    MADA CHAR(7) PRIMARY KEY,
    TENDA VARCHAR2(40),
    NGAYBD DATE,
    PHONG CHAR(7)
);

CREATE TABLE QLDA_PHANCONG(
    MANV VARCHAR2(30),
    MADA CHAR(7),
    THOIGIAN DATE,
    CONSTRAINT PHCONG_PK PRIMARY KEY(MANV, MADA)
);

ALTER TABLE QLDA.QLDA_PHONGBAN MODIFY TRPHG VARCHAR2(128);
ALTER TABLE QLDA.QLDA_NHANVIEN MODIFY MANV VARCHAR2(128);
ALTER TABLE QLDA.QLDA_NHANVIEN MODIFY MANQL VARCHAR2(128);
ALTER TABLE QLDA.QLDA_PHANCONG MODIFY MANV VARCHAR2(128);
ALTER TABLE QLDA.QLDA_NHANVIEN MODIFY LUONG NVARCHAR2(176);
ALTER TABLE QLDA.QLDA_NHANVIEN MODIFY PHUCAP NVARCHAR2(176);
ALTER TABLE QLDA.QLDA_PHONGBAN MODIFY MAPB CHAR(7);

--Khóa ngoại
ALTER TABLE QLDA.QLDA_NHANVIEN ADD CONSTRAINT QLDA_NHANVIEN_FK1 FOREIGN KEY (MANQL) REFERENCES QLDA.QLDA_NHANVIEN(MANV);
ALTER TABLE QLDA.QLDA_NHANVIEN ADD CONSTRAINT QLDA_NHANVIEN_FK2 FOREIGN KEY (MAPB) REFERENCES QLDA.QLDA_PHONGBAN(MAPB);
ALTER TABLE QLDA.QLDA_DEAN ADD CONSTRAINT QLDA_DEAN_FK1 FOREIGN KEY (PHONG) REFERENCES QLDA.QLDA_PHONGBAN(MAPB);
ALTER TABLE QLDA.QLDA_PHANCONG ADD CONSTRAINT QLDA_PHANCONG_FK1 FOREIGN KEY (MANV) REFERENCES QLDA.QLDA_NHANVIEN(MANV);
ALTER TABLE QLDA.QLDA_PHANCONG ADD CONSTRAINT QLDA_PHANCONG_FK2 FOREIGN KEY (MADA) REFERENCES QLDA_DEAN(MADA);
ALTER TABLE QLDA.QLDA_PHONGBAN ADD CONSTRAINT QLDA_PHONGBAN_FK1 FOREIGN KEY (TRPHG) REFERENCES QLDA.QLDA_NHANVIEN(MANV);

/* Drop khóa ngoại
ALTER TABLE QLDA.QLDA_NHANVIEN DROP CONSTRAINT QLDA_NHANVIEN_FK1;
ALTER TABLE QLDA.QLDA_NHANVIEN DROP CONSTRAINT QLDA_NHANVIEN_FK2;
ALTER TABLE QLDA.QLDA_DEAN DROP CONSTRAINT QLDA_DEAN_FK1;
ALTER TABLE QLDA.QLDA_PHANCONG DROP CONSTRAINT QLDA_PHANCONG_FK1;
ALTER TABLE QLDA.QLDA_PHANCONG DROP CONSTRAINT QLDA_PHANCONG_FK2;
ALTER TABLE QLDA.QLDA_PHONGBAN DROP CONSTRAINT QLDA_PHONGBAN_FK1;
*/


--Kiểm tra table đã tạo và owner
select table_name, owner from all_tables where owner = 'QLDA';
--xem tất cả data_type
select role from dba_roles;

select * from tabs;

--Xem danh sách khóa ngoại và khóa chính
select * from user_constraints;
--Xem kiểu dữ liệu của cột trong bảng
select * from user_tab_columns;

--Tạo biến char(7) và varchar2(30) và so sánh
declare
    v_char varchar2(10);
    v_varchar varchar2(30);
begin
    v_char := '1234567';
    v_varchar := '1234567';
    if(v_char = v_varchar) then dbms_output.put_line('Bằng'); end if;
    if(v_char <> v_varchar) then dbms_output.put_line('Khác'); end if;
end;

SELECT table_name FROM user_tables;
--Get column name
SELECT * FROM user_tab_columns WHERE table_name = 'TEST';
--Danh sách Khóa ngoại
SELECT * FROM user_constraints; --WHERE constraint_type = 'R';
begin
    for r in ( select table_name, constraint_name
               from user_constraints
               where table_name = 'TEST')
    loop
        execute immediate 'alter table '|| r.table_name
                          ||' drop constraint '|| r.constraint_name;
    end loop;
end;
CREATE TABLE TEST(
    TEST INT
    --PRIMARY KEY(MANV, MADA)
);
DROP TABLE QLDA.TEST cascade CONSTRAINTS;
--Delete constraint name
DELETE FROM QLDA_NHANVIEN WHERE MANV = 'NV301';
DELETE FROM QLDA_PHONGBAN WHERE MAPB = 'PB009';

