CREATE TABLE QLDA_PHONGBAN(
    MAPB NUMBER(4) PRIMARY KEY,
    TENPB VARCHAR(30),
    TRPHG NUMBER(10)
);

CREATE TABLE QLDA_NHANVIEN(
    MANV NUMBER(10) PRIMARY KEY,
    TENNV VARCHAR(20),
    PHAI VARCHAR(3),
    NGAYSINH DATE,
    DIACHI VARCHAR(20),
    SODT NUMBER(10),
    LUONG NUMBER(7, 2),
    PHUCAP NUMBER(7, 2),
    VAITRO VARCHAR(30),
    MANQL NUMBER(10),
    PHG NUMBER(4) REFERENCES QLDA_PHONGBAN(MAPB)
);

CREATE TABLE QLDA_DEAN(
    MADA NUMBER(10) PRIMARY KEY,
    TENDA VARCHAR(30),
    NGAYBD DATE,
    PHONG NUMBER(4) REFERENCES QLDA_PHONGBAN(MAPB)
);

CREATE TABLE QLDA_PHANCONG(
    MANV NUMBER(10) REFERENCES QLDA_NHANVIEN(MANV),
    MADA NUMBER(10) REFERENCES QLDA_DEAN(MADA),
    THOIGIAN DATE,
    CONSTRAINT PHCONG_PK PRIMARY KEY(MANV, MADA)
);

ALTER TABLE QLDA_PHONGBAN ADD CONSTRAINT TRPHG_FK FOREIGN KEY (TRPHG) REFERENCES QLDA_NHANVIEN(MANV);
