----------------- MÃ HOÁ -----------------
  -- Mã hoá thông tin LUONG và PHUCAP
  -- Tạo package hỗ trợ mã hoá - giải mã
CREATE OR REPLACE PACKAGE ENCRYPT_DECRYPT AS
  FUNCTION ENCRYPT_NHANVIEN_LUONG(
    P_IN IN NVARCHAR2,
    P_KEY IN CHAR
  ) RETURN RAW DETERMINISTIC;
  FUNCTION DECRYPT_NHANVIEN_LUONG(
    P_IN IN RAW,
    P_KEY IN CHAR
  ) RETURN NVARCHAR2 DETERMINISTIC;
  FUNCTION ENCRYPT_NHANVIEN_PHUCAP(
    P_IN IN NVARCHAR2,
    P_KEY IN CHAR
  ) RETURN RAW DETERMINISTIC;
  FUNCTION DECRYPT_NHANVIEN_PHUCAP(
    P_IN IN RAW,
    P_KEY IN CHAR
  ) RETURN NVARCHAR2 DETERMINISTIC;
END ENCRYPT_DECRYPT;
/
--Xóa package nếu tồn tại
--DROP PACKAGE ENCRYPT_DECRYPT;

-- Cài đặt các function trong package trên
CREATE OR REPLACE PACKAGE BODY ENCRYPT_DECRYPT IS
  ENCRYPTION_TYPE PLS_INTEGER := DBMS_CRYPTO.ENCRYPT_DES +DBMS_CRYPTO.CHAIN_CBC +DBMS_CRYPTO.PAD_PKCS5;
  FUNCTION ENCRYPT_NHANVIEN_LUONG(
    P_IN IN NVARCHAR2,
    P_KEY IN CHAR
  ) RETURN RAW DETERMINISTIC IS
    ENCRYPTED_RAW RAW(2000);
  BEGIN
    ENCRYPTED_RAW := DBMS_CRYPTO.ENCRYPT( SRC => UTL_RAW.CAST_TO_RAW(P_IN), TYP => ENCRYPTION_TYPE, KEY => UTL_RAW.CAST_TO_RAW(P_KEY) );
    RETURN ENCRYPTED_RAW;
  END ENCRYPT_NHANVIEN_LUONG;
  FUNCTION DECRYPT_NHANVIEN_LUONG(
    P_IN IN RAW,
    P_KEY IN CHAR
  ) RETURN NVARCHAR2 DETERMINISTIC IS
    DECRYPTED_RAW RAW(2000);
  BEGIN
    DECRYPTED_RAW := DBMS_CRYPTO.DECRYPT( SRC => P_IN, TYP => ENCRYPTION_TYPE, KEY => UTL_RAW.CAST_TO_RAW(P_KEY) );
    RETURN UTL_RAW.CAST_TO_NVARCHAR2(DECRYPTED_RAW);
  END DECRYPT_NHANVIEN_LUONG;
  
  FUNCTION ENCRYPT_NHANVIEN_PHUCAP(
    P_IN IN NVARCHAR2,
    P_KEY IN CHAR
  ) RETURN RAW DETERMINISTIC IS
    ENCRYPTED_RAW RAW(2000);
  BEGIN
    ENCRYPTED_RAW := DBMS_CRYPTO.ENCRYPT( SRC => UTL_RAW.CAST_TO_RAW(P_IN), TYP => ENCRYPTION_TYPE, KEY => UTL_RAW.CAST_TO_RAW(P_KEY) );
    RETURN ENCRYPTED_RAW;
  END ENCRYPT_NHANVIEN_PHUCAP;
  FUNCTION DECRYPT_NHANVIEN_PHUCAP(
    P_IN IN RAW,
    P_KEY IN CHAR
  ) RETURN NVARCHAR2 DETERMINISTIC IS
    DECRYPTED_RAW RAW(2000);
  BEGIN
    DECRYPTED_RAW := DBMS_CRYPTO.DECRYPT( SRC => P_IN, TYP => ENCRYPTION_TYPE, KEY => UTL_RAW.CAST_TO_RAW(P_KEY) );
    RETURN UTL_RAW.CAST_TO_NVARCHAR2(DECRYPTED_RAW);
  END DECRYPT_NHANVIEN_PHUCAP;
END ENCRYPT_DECRYPT;
/

-- Mã hoá tất cả thông tin lương và phụ cấp trong bảng nhân viên
UPDATE QLDA_NHANVIEN NV1
SET
  LUONG = (
    SELECT ENCRYPT_DECRYPT.ENCRYPT_NHANVIEN_LUONG(LUONG, '3F569C3F19E25B18B2C12B975F9BC5BB') FROM QLDA_NHANVIEN NV2 WHERE NV1.MANV = NV2.MANV
  );
COMMIT;
/
UPDATE QLDA_NHANVIEN NV1
SET
  PHUCAP = (
    SELECT ENCRYPT_DECRYPT.ENCRYPT_NHANVIEN_PHUCAP(PHUCAP, '3F569C3F19E25B18B2C12B975F9BC5BB') FROM QLDA_NHANVIEN NV2 WHERE NV1.MANV = NV2.MANV
  );
COMMIT;
/

-- Tự động mã hoá thông tin LUONG VA PHU CAP khi thêm, sửa
CREATE OR REPLACE TRIGGER auto_encrypted_nhanvien BEFORE
    INSERT OR UPDATE ON qlda.qlda_nhanvien
    FOR EACH ROW
DECLARE BEGIN
    if (INSERTING) then
      :new.luong := encrypt_decrypt.encrypt_nhanvien_luong(:new.luong, '3F569C3F19E25B18B2C12B975F9BC5BB');
    end if;

    if (INSERTING) then
      :new.phucap := encrypt_decrypt.encrypt_nhanvien_phucap(:new.phucap, '3F569C3F19E25B18B2C12B975F9BC5BB');
    end if;

    if (:new.luong is not null and UPDATING and ((:new.luong <> :old.luong) or (:old.luong is null))) then
      :new.luong := encrypt_decrypt.encrypt_nhanvien_luong(:new.luong, '3F569C3F19E25B18B2C12B975F9BC5BB');
    end if;

    if (:new.phucap is not null and UPDATING and ((:new.phucap <> :old.phucap) or (:old.phucap is null))) then
      :new.phucap := encrypt_decrypt.encrypt_nhanvien_phucap(:new.phucap, '3F569C3F19E25B18B2C12B975F9BC5BB');
    end if;
END;
 -- Câu lệnh test trigger AUTO_ENCRYPTED_NHANVIEN
INSERT INTO QLDA_NHANVIEN (MANV,TENNV, PHAI, NGAYSINH, DIACHI, SODT, LUONG, PHUCAP, VAITRO, MANQL, MAPB) VALUES (
         'NV400',
         'Nhân viên 400',
         'Nam',
         TO_DATE('01-JAN-1970', 'DD-MON-YYYY'),
         'HCM',
         '0123456789',
         NULL,
         NULL,
         'Nhân viên',
         'QL001',
         'PB001'
      );
    UPDATE QLDA_NHANVIEN SET LUONG = 10000000, PHUCAP = 1000000 WHERE MANV = 'NV400';
    SELECT * FROM QLDA_NHANVIEN WHERE MANV='NV400';
--select LUONG, phucap FROM QLDA_NHANVIEN WHERE MANV='NV400';
--Xóa hàm
--DROP TRIGGER auto_encrypted_nhanvien;
GRANT EXECUTE ON QLDA.ENCRYPT_DECRYPT TO NV;
GRANT EXECUTE ON QLDA.ENCRYPT_DECRYPT TO QL;
GRANT EXECUTE ON QLDA.ENCRYPT_DECRYPT TO TP;
GRANT EXECUTE ON QLDA.ENCRYPT_DECRYPT TO TC;
GRANT EXECUTE ON QLDA.ENCRYPT_DECRYPT TO NS;
GRANT EXECUTE ON QLDA.ENCRYPT_DECRYPT TO TA;
GRANT EXECUTE ON QLDA.ENCRYPT_DECRYPT TO TA;
--GRANT EXECUTE ON QLDA.ENCRYPT_DECRYPT TO NEWUSER;
--REVOKE EXECUTE ON QLDA.ENCRYPT_DECRYPT FROM NEWUSER;


SELECT
    luong,
    encrypt_decrypt.decrypt_nhanvien_luong(luong, '3F569C3F19E25B18B2C12B975F9BC5BB') AS luong_giaima,
    phucap,
    encrypt_decrypt.decrypt_nhanvien_phucap(phucap, '3F569C3F19E25B18B2C12B975F9BC5BB') AS phucap_giaima
FROM
    QLDA.qlda_nhanvien;

--DELETE FROM QLDA_NHANVIEN WHERE MANV='NV400';