UPDATE QLDA.V_QLDA_NHANVIEN_NS
SET SODT = '0190949000'
WHERE MANV = 'NV030'; COMMIT;
SELECT * FROM QLDA.V_QLDA_NHANVIEN_NS;

INSERT INTO QLDA.V_QLDA_NHANVIEN_NS(MANV, TENNV, NGAYSINH) VALUES ('NV303', 'Nhân viên 303', TO_DATE('09/01/1997', 'DD/MM/YYYY')); COMMIT;
--INSERT INTO QLDA.V_QLDA_NHANVIEN_NS(MANV, TENNV, NGAYSINH) VALUES ('NV302', 'Nhân viên 302', TO_DATE('09/01/1997', 'DD/MM/YYYY')); COMMIT;
INSERT INTO QLDA.V_QLDA_NHANVIEN_NS VALUES('NV393', 'Nguyễn Văn C', 'Nam', TO_DATE('22/03/2009', 'DD/MM/YYYY'), 'Hà Nội', '0367877666', NULL, NULL, 'Nhân viên', 'QL001', 'PB001'); COMMIT;
SELECT * FROM QLDA.V_QLDA_NHANVIEN_NS;

UPDATE QLDA.V_QLDA_NHANVIEN_NS
SET PHUCAP = 115
WHERE MANV = 'NV302'; COMMIT;
SELECT * FROM QLDA.V_QLDA_NHANVIEN_NS;


UPDATE QLDA.QLDA_PHONGBAN
SET TENPB = 'Truyền thông'
WHERE MAPB = 'PB002'; COMMIT;
SELECT * FROM QLDA.QLDA_PHONGBAN;

INSERT INTO QLDA.QLDA_PHONGBAN(MAPB, TENPB) VALUES ('PB009', 'Điều hành'); COMMIT;
SELECT * FROM QLDA.QLDA_PHONGBAN;

SELECT * FROM QLDA.QLDA_PHONGBAN;
SELECT * FROM QLDA.QLDA_DEAN;
SELECT * FROM QLDA.QLDA_PHANCONG;