UPDATE QLDA.QLDA_NHANVIEN SET NgaySinh = TO_DATE('03/06/1972', 'DD/MM/YYYY'), DiaChi = 'HCM 383', SODT = '0123456789' WHERE MaNV = 'NV001';
COMMIT;
SELECT * FROM QLDA.QLDA_NHANVIEN;

SELECT * FROM QLDA.QLDA_PHONGBAN;
SELECT * FROM QLDA.QLDA_DEAN;

SELECT VaiTro FROM QLDA.QLDA_NHANVIEN WHERE MANV = 'NV001'
select sys_context('userenv', 'current_user') from dual;