UPDATE QLDA.V_QLDA_NHANVIEN SET NgaySinh = TO_DATE('03/06/1972', 'DD/MM/YYYY'), DiaChi = 'HCM 383', SODT = '0123456789' WHERE MaNV = 'NV001';
COMMIT;
SELECT * FROM QLDA.V_QLDA_NHANVIEN WHERE MANV = 'NV002';

SELECT * FROM QLDA.QLDA_PHONGBAN;
SELECT * FROM QLDA.QLDA_DEAN;
SELECT * FROM QLDA.QLDA_PHANCONG;

SELECT NV1.*, QLDA.encrypt_decrypt.decrypt_nhanvien_luong(luong, QLDA.ENCRYPT_DECRYPT.CREATE_KEY((SELECT MANV FROM QLDA.QLDA_NHANVIEN NV2 WHERE NV1.MANV = NV2.MANV), QLDA.ENCRYPT_DECRYPT.SEQ_NUM)) AS luong_giaima,
QLDA.encrypt_decrypt.decrypt_nhanvien_phucap(phucap, QLDA.ENCRYPT_DECRYPT.CREATE_KEY((SELECT MANV FROM QLDA.QLDA_NHANVIEN NV2 WHERE NV1.MANV = NV2.MANV), QLDA.ENCRYPT_DECRYPT.SEQ_NUM)) AS phucap_giaima FROM QLDA.QLDA_NHANVIEN NV1 WHERE MANV = 'NV002';
