UPDATE QLDA.QLDA_NHANVIEN
SET NGAYSINH = TO_DATE('01/03/1992', 'DD/MM/YYYY')
WHERE MANV = 'NV001';
COMMIT;
SELECT * FROM QLDA.QLDA_NHANVIEN;

SELECT * FROM QLDA.QLDA_PHONGBAN;
SELECT * FROM QLDA.QLDA_DEAN;
