SELECT * FROM QLDA.V_QLDA_NHANVIEN_NS;
SELECT * FROM QLDA.V_QLDA_PHANCONG_QL;
--SELECT * FROM QLDA.QLDA_PHANCONG;


SELECT * FROM QLDA.QLDA_PHONGBAN;
SELECT * FROM QLDA.QLDA_DEAN;

UPDATE QLDA.V_QLDA_NHANVIEN_NS
SET SODT = '0986285783'
WHERE MANV = 'QL001';
COMMIT;
SELECT * FROM QLDA.V_QLDA_NHANVIEN_NS;