SELECT * FROM QLDA.QLDA_NHANVIEN;

UPDATE QLDA.QLDA_NHANVIEN
SET SODT = '0389399999'
WHERE MANV = 'TA001'; COMMIT;
SELECT * FROM QLDA.QLDA_NHANVIEN;

INSERT INTO QLDA.QLDA_DEAN(MADA, TENDA, NGAYBD, PHONG) VALUES ('DP33333', 'Tăng học phí', TO_DATE('01/01/2019','DD/MM/YYYY'), 'PB005'); COMMIT;
SELECT * FROM QLDA.QLDA_DEAN;

UPDATE QLDA.QLDA_DEAN
SET TENDA = 'Tự chủ tài chính'
WHERE MADA = 'DP33333'; COMMIT;
SELECT * FROM QLDA.QLDA_DEAN;

DELETE FROM QLDA.QLDA_DEAN
WHERE MADA = 'DP33333'; COMMIT;
SELECT * FROM QLDA.QLDA_DEAN;

SELECT * FROM QLDA.QLDA_PHONGBAN;
SELECT * FROM QLDA.QLDA_DEAN;
