INSERT INTO QLDA.QLDA_PHANCONG(MANV, MADA, THOIGIAN)
VALUES('NV002', 'DP22222', (TO_DATE('15/1/2023', 'DD/MM/YYYY')));
COMMIT;
SELECT * FROM QLDA.QLDA_PHANCONG;

INSERT INTO QLDA.QLDA_PHANCONG(MANV, MADA, THOIGIAN)
VALUES('NV033', 'DP22222', (TO_DATE('15/1/2023', 'DD/MM/YYYY')));
COMMIT;
SELECT * FROM QLDA.QLDA_PHANCONG;

UPDATE QLDA.QLDA_PHANCONG
SET THOIGIAN = TO_DATE('11/1/2023', 'DD/MM/YYYY')
WHERE MANV = 'NV002';
COMMIT;
SELECT * FROM QLDA.QLDA_PHANCONG;

UPDATE QLDA.QLDA_PHANCONG
SET THOIGIAN = TO_DATE('11/1/2023', 'DD/MM/YYYY')
WHERE MANV = 'NV040';
COMMIT;
SELECT * FROM QLDA.QLDA_PHANCONG;

DELETE FROM QLDA.QLDA_PHANCONG WHERE MANV = 'NV002';
COMMIT;
SELECT * FROM QLDA.QLDA_PHANCONG;

DELETE FROM QLDA.QLDA_PHANCONG WHERE MANV = 'NV040';
COMMIT;
SELECT * FROM QLDA.QLDA_PHANCONG;

SELECT * FROM QLDA.QLDA_NHANVIEN;

UPDATE QLDA.QLDA_NHANVIEN
SET NGAYSINH = TO_DATE('01/03/1992', 'DD/MM/YYYY')
WHERE MANV = 'TP001';
COMMIT;
SELECT * FROM QLDA.QLDA_NHANVIEN;

SELECT * FROM QLDA.QLDA_PHONGBAN;
SELECT * FROM QLDA.QLDA_DEAN;

--Kiểm tra OLS
ALTER SESSION SET CONTAINER = PDB1;
--Đăng nhập vào mỗi TP001,002,003 để xem sự khác nhau của thông báo.
SELECT * FROM QLDA_PDB1.THONGBAO;
